
---
 - name: Modify Grub
   hosts: Linux
   become: yes

   tasks:
   - name: Add Parameter net.ifnames=0 to /etc/default/grub
     ansible.builtin.lineinfile:
      path: /etc/default/grub
      backrefs: yes
      state: present
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames=)\"[^\"]+)(\".*)'
      line: '\1 net.ifnames=0\2'


   - name: Add Parameter biosdevname=0 to /etc/default/grub
     ansible.builtin.lineinfile:
      path: /etc/default/grub
      backrefs: yes
      state: present
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* biosdevname=)\"[^\"]+)(\".*)'
      line: '\1 biosdevname=0\2'


   - name: Execute Grub2-mkconfig
     ansible.builtin.command: /usr/sbin/grub2-mkconfig

