---
 - name: Add Users to Server
   hosts: node_1
   become: yes

   vars:
     users:
      - Alice
      - Bob
      - Carol
   vars_files:
     - password.yaml

   tasks:
    - name: Set Variable
      set_fact:
       password: "{{ upassword | password_hash('sha512') }}"

    - name: Add the user {{ item }}
      ansible.builtin.user:
         name: "{{ item }}"
         password: "{{ password }}"
         shell: /bin/bash
         update_password: on_create
         comment: '{{ item }}.example.com'
         create_home: yes
      with_items: "{{ users }}"


